// ---------- CODE SYSTEM (تخصيص التطبيق → نظام الأكواد) ----------
// The owner designs HOW the app builds the codes it generates: a code is a
// TEMPLATE = ordered PARTS joined by a SEPARATOR (dash by default), e.g.
//
//   [text "P"] - [timestamp]                →  P-1702655732293
//   [church] - [class] - [date YYMMDD] - [random 4]  →  STM-C1-231215-4F7K
//
// Part types:
//   text       fixed literal (prefix / suffix)
//   timestamp  the moment of generation in milliseconds  → 1702655732293
//   date       formatted generation date (YYYYMMDD · YYMMDD · YYYY …)
//   random     N random characters (letters+digits · digits · letters · hex)
//   church / service / class  the ABBREVIATION the owner gave that scope
//              (تخصيص الأكواد → اختصارات الكنائس والخدمات والفصول), with a
//              fallback text when the scope has none / isn't selected.
//
// One DEFAULT SYSTEM is shared by every generator; each GENERATOR in the app
// (كود المخدوم · كود الخادم · كود منتج المتجر · كود تذكرة المناسبة) may:
//   'default' → follow the default system
//   'custom'  → have its own template
//   'legacy'  → keep the app's original built-in generator (P-XXXXXXXX …)
//
// Stored in `app_settings.key = 'codes'` (migration 0040, owner-write /
// all-read / realtime; anonymous signup reads it through `code_settings()`).
// `public.render_code()` in SQL mirrors `renderTemplate()` below so codes
// generated by the database (occasion tickets) follow the same design.
// Codes must stay within [A-Za-z0-9._-] — a servant's code is also his login
// name (see `code_to_user_id`).

export const CODES_SETTING_KEY = 'codes';

// ---------- generators (the places in the app that create codes) ----------
export type CodeKind = 'person' | 'servant' | 'store_item' | 'ticket' | 'family';

export interface CodeGeneratorDef {
  key: CodeKind;
  label: string;
  desc: string;
  /** where in the app this generator is used */
  where: string;
  /** what the built-in (legacy) generator produces */
  legacyExample: string;
  /** rendered by the database (SQL) rather than the app */
  serverSide?: boolean;
}

export const CODE_GENERATORS: CodeGeneratorDef[] = [
  {
    key: 'person', label: 'كود المخدوم', desc: 'الكود / الرقم القومي البديل للمخدوم — يُطبع على بطاقة الـ QR',
    where: 'إضافة مخدوم (فردي و جماعي «AUTO») · تعديل كود المخدوم', legacyExample: 'P-4F7K9Q2M',
  },
  {
    key: 'servant', label: 'كود الخادم', desc: 'كود الخادم عند التسجيل — هو أيضاً اسم الدخول',
    where: 'صفحة إنشاء حساب خادم → توليد كود', legacyExample: 'P-4F7K9Q2M',
  },
  {
    key: 'store_item', label: 'كود منتج المتجر', desc: 'كود المنتج في متجر النقاط (فريد داخل الكنيسة)',
    where: 'وحدة إستبدال النقاط → إضافة منتج', legacyExample: 'ST-4F7K2Q',
  },
  {
    key: 'ticket', label: 'كود تذكرة المناسبة', desc: 'كود التذكرة عند تسجيل مخدوم في مناسبة — تُولَّد في قاعدة البيانات',
    where: 'وحدة الفعاليات → تسجيل مشارك', legacyExample: 'T-4F7K9Q2M1B', serverSide: true,
  },
  {
    key: 'family', label: 'كود العائلة', desc: 'كود العائلة (QR العائلة) — مسحه في الماسح يعرض كل أفراد العائلة',
    where: 'وحدة العائلات → عائلة جديدة → توليد كود', legacyExample: 'F-4F7K9Q',
  },
];
export const CODE_GENERATOR_BY_KEY: Record<CodeKind, CodeGeneratorDef> = Object.fromEntries(
  CODE_GENERATORS.map((g) => [g.key, g])
) as Record<CodeKind, CodeGeneratorDef>;
export const CODE_KINDS = CODE_GENERATORS.map((g) => g.key) as CodeKind[];

// ---------- parts ----------
export type PartType = 'text' | 'timestamp' | 'date' | 'random' | 'church' | 'service' | 'class';
export type DateFormat = 'YYYYMMDD' | 'YYMMDD' | 'DDMMYYYY' | 'DDMMYY' | 'YYYYMM' | 'YYMM' | 'YYYY' | 'YY';
export type RandomCharset = 'alnum' | 'digits' | 'letters' | 'hex';
export type ScopePartType = 'church' | 'service' | 'class';

export interface TextPart { type: 'text'; value: string }
export interface TimestampPart { type: 'timestamp' }
export interface DatePart { type: 'date'; format: DateFormat }
export interface RandomPart { type: 'random'; length: number; charset: RandomCharset }
export interface ScopePart { type: ScopePartType; fallback: string }
export type CodePart = TextPart | TimestampPart | DatePart | RandomPart | ScopePart;

export type CodeCase = 'none' | 'upper' | 'lower';

export interface CodeTemplate {
  parts: CodePart[];
  /** joined between non-empty parts — '' allowed (no separator) */
  separator: string;
  case: CodeCase;
}

export type GeneratorMode = 'default' | 'custom' | 'legacy';
export interface GeneratorConfig {
  mode: GeneratorMode;
  /** the generator's own template (used when mode = 'custom') */
  template?: CodeTemplate;
}

export interface ScopeAbbreviations {
  churches: Record<string, string>;
  services: Record<string, string>;
  classes: Record<string, string>;
}

export interface CodesConfig {
  version: 1;
  /** the default system followed by every generator in 'default' mode */
  default: CodeTemplate;
  generators: Record<CodeKind, GeneratorConfig>;
  scopes: ScopeAbbreviations;
}

export interface CodeContext {
  churchId?: string | null;
  serviceId?: string | null;
  classId?: string | null;
  /** generation moment (ms) — bulk imports pass a monotonic clock so timestamp codes never collide */
  now?: number;
}

// ---------- limits & sanitizing ----------
export const MAX_PARTS = 8;
export const MAX_TEXT_LENGTH = 12;
export const MAX_SEPARATOR_LENGTH = 3;
export const MAX_ABBREVIATION_LENGTH = 8;
export const MIN_RANDOM = 1;
export const MAX_RANDOM = 16;

/** allowed in every literal segment — keeps the code a valid login name too */
export const SAFE_SEGMENT_RE = /^[A-Za-z0-9._-]*$/;
export const sanitizeSegment = (s: string, max: number): string =>
  s.replace(/[^A-Za-z0-9._-]/g, '').slice(0, max);

export const PART_TYPE_LABELS: Record<PartType, string> = {
  text: 'نص ثابت',
  timestamp: 'الوقت (مللي ثانية)',
  date: 'التاريخ',
  random: 'عشوائي',
  church: 'اختصار الكنيسة',
  service: 'اختصار الخدمة',
  class: 'اختصار الفصل',
};

export const PART_TYPE_HINTS: Record<PartType, string> = {
  text: 'بادئة أو لاحقة ثابتة مثل P أو ST',
  timestamp: 'لحظة التوليد بالمللي ثانية مثل 1702655732293 — فريد عملياً',
  date: 'تاريخ التوليد بصيغة تختارها',
  random: 'حروف وأرقام عشوائية بطول تختاره',
  church: 'اختصار الكنيسة المختارة (تحدده في قسم الاختصارات)',
  service: 'اختصار الخدمة المختارة',
  class: 'اختصار الفصل المختار',
};

export const DATE_FORMAT_LABELS: Record<DateFormat, string> = {
  YYYYMMDD: 'سنة-شهر-يوم (20231215)',
  YYMMDD: 'سنة مختصرة-شهر-يوم (231215)',
  DDMMYYYY: 'يوم-شهر-سنة (15122023)',
  DDMMYY: 'يوم-شهر-سنة مختصرة (151223)',
  YYYYMM: 'سنة-شهر (202312)',
  YYMM: 'سنة مختصرة-شهر (2312)',
  YYYY: 'السنة (2023)',
  YY: 'السنة مختصرة (23)',
};

export const RANDOM_CHARSET_LABELS: Record<RandomCharset, string> = {
  alnum: 'حروف وأرقام (بدون المتشابهة)',
  digits: 'أرقام فقط',
  letters: 'حروف فقط',
  hex: 'ست عشري (0-9 A-F)',
};

export const CASE_LABELS: Record<CodeCase, string> = {
  none: 'كما هو',
  upper: 'حروف كبيرة',
  lower: 'حروف صغيرة',
};

export const SCOPE_PART_TYPES: ScopePartType[] = ['church', 'service', 'class'];
export const isScopePart = (p: CodePart): p is ScopePart =>
  p.type === 'church' || p.type === 'service' || p.type === 'class';

// ---------- factories ----------
export const newPart = (type: PartType): CodePart => {
  switch (type) {
    case 'text': return { type, value: 'P' };
    case 'timestamp': return { type };
    case 'date': return { type, format: 'YYYYMMDD' };
    case 'random': return { type, length: 6, charset: 'alnum' };
    default: return { type, fallback: '' };
  }
};

export const text = (value: string): TextPart => ({ type: 'text', value });
export const timestamp = (): TimestampPart => ({ type: 'timestamp' });
export const date = (format: DateFormat = 'YYYYMMDD'): DatePart => ({ type: 'date', format });
export const random = (length = 6, charset: RandomCharset = 'alnum'): RandomPart => ({ type: 'random', length, charset });
export const scope = (type: ScopePartType, fallback = ''): ScopePart => ({ type, fallback });

export const template = (parts: CodePart[], separator = '-', kase: CodeCase = 'none'): CodeTemplate =>
  ({ parts, separator, case: kase });

// ---------- defaults & presets ----------
/** the default system when the owner saves without changing it: P-1702655732293 */
export const DEFAULT_TEMPLATE: CodeTemplate = template([text('P'), timestamp()]);

export const EMPTY_SCOPES: ScopeAbbreviations = { churches: {}, services: {}, classes: {} };

/** nothing saved → every generator keeps the app's original behaviour */
export const DEFAULT_CODES: CodesConfig = {
  version: 1,
  default: DEFAULT_TEMPLATE,
  generators: {
    person: { mode: 'legacy' },
    servant: { mode: 'legacy' },
    store_item: { mode: 'legacy' },
    ticket: { mode: 'legacy' },
    family: { mode: 'legacy' },
  },
  scopes: EMPTY_SCOPES,
};

export interface TemplatePreset { key: string; label: string; template: CodeTemplate }
export const TEMPLATE_PRESETS: TemplatePreset[] = [
  { key: 'timestamp', label: 'الوقت فقط', template: template([timestamp()]) },
  { key: 'prefix_timestamp', label: 'بادئة + الوقت', template: template([text('P'), timestamp()]) },
  { key: 'scope_timestamp', label: 'كنيسة-خدمة-فصل-الوقت', template: template([scope('church'), scope('service'), scope('class'), timestamp()]) },
  { key: 'church_class_date_random', label: 'كنيسة-فصل-تاريخ-عشوائي', template: template([scope('church'), scope('class'), date('YYMMDD'), random(4)]) },
  { key: 'date_random', label: 'تاريخ + عشوائي', template: template([date('YYYYMMDD'), random(4)]) },
  { key: 'prefix_random', label: 'بادئة + عشوائي (الطريقة الأصلية)', template: template([text('P'), random(8)]) },
  { key: 'year_random_digits', label: 'سنة + 6 أرقام', template: template([date('YYYY'), random(6, 'digits')]) },
];

// ---------- legacy (built-in) generators ----------
const ALNUM = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const CHARSETS: Record<RandomCharset, string> = {
  alnum: ALNUM,
  digits: '0123456789',
  letters: 'ABCDEFGHJKLMNPQRSTUVWXYZ',
  hex: '0123456789ABCDEF',
};

const randomChars = (n: number, charset: RandomCharset): string => {
  const alphabet = CHARSETS[charset] ?? ALNUM;
  let s = '';
  for (let i = 0; i < n; i++) s += alphabet[Math.floor(Math.random() * alphabet.length)];
  return s;
};

/** what the app produced before the code system existed */
export const legacyCode = (kind: CodeKind): string => {
  switch (kind) {
    case 'store_item': return `ST-${randomChars(6, 'alnum')}`;
    case 'ticket': return `T-${randomChars(10, 'hex')}`;
    case 'family': return `F-${randomChars(6, 'alnum')}`;
    default: return `P-${randomChars(8, 'alnum')}`;
  }
};

// ---------- rendering ----------
const pad2 = (n: number) => String(n).padStart(2, '0');

export const formatDate = (d: Date, format: DateFormat): string => {
  const yyyy = String(d.getFullYear());
  const yy = yyyy.slice(2);
  const mm = pad2(d.getMonth() + 1);
  const dd = pad2(d.getDate());
  switch (format) {
    case 'YYYYMMDD': return `${yyyy}${mm}${dd}`;
    case 'YYMMDD': return `${yy}${mm}${dd}`;
    case 'DDMMYYYY': return `${dd}${mm}${yyyy}`;
    case 'DDMMYY': return `${dd}${mm}${yy}`;
    case 'YYYYMM': return `${yyyy}${mm}`;
    case 'YYMM': return `${yy}${mm}`;
    case 'YYYY': return yyyy;
    case 'YY': return yy;
    default: return `${yyyy}${mm}${dd}`;
  }
};

const scopeAbbreviation = (part: ScopePart, ctx: CodeContext, scopes: ScopeAbbreviations): string => {
  const id = part.type === 'church' ? ctx.churchId : part.type === 'service' ? ctx.serviceId : ctx.classId;
  const map = part.type === 'church' ? scopes.churches : part.type === 'service' ? scopes.services : scopes.classes;
  const abbr = id ? map[id] : undefined;
  return (abbr && abbr.trim()) || part.fallback || '';
};

/** Render ONE part — '' means "skip" (no separator is emitted for it). */
export const renderPart = (part: CodePart, ctx: CodeContext, scopes: ScopeAbbreviations): string => {
  switch (part.type) {
    case 'text': return part.value;
    case 'timestamp': return String(ctx.now ?? Date.now());
    case 'date': return formatDate(new Date(ctx.now ?? Date.now()), part.format);
    case 'random': return randomChars(part.length, part.charset);
    default: return scopeAbbreviation(part, ctx, scopes);
  }
};

export const applyCase = (s: string, c: CodeCase): string =>
  c === 'upper' ? s.toUpperCase() : c === 'lower' ? s.toLowerCase() : s;

/** Render a full template — empty parts are dropped so no double separators appear. */
export const renderTemplate = (t: CodeTemplate, ctx: CodeContext = {}, scopes: ScopeAbbreviations = EMPTY_SCOPES): string => {
  const segs = t.parts.map((p) => renderPart(p, ctx, scopes)).filter((s) => s.length > 0);
  return applyCase(segs.join(t.separator), t.case);
};

/** The template a generator actually uses — null = legacy built-in generator. */
export const resolveTemplate = (cfg: CodesConfig | null | undefined, kind: CodeKind): CodeTemplate | null => {
  if (!cfg) return null;
  const g = cfg.generators[kind] ?? { mode: 'legacy' };
  if (g.mode === 'legacy') return null;
  if (g.mode === 'custom' && g.template && g.template.parts.length > 0) return g.template;
  return cfg.default.parts.length > 0 ? cfg.default : null;
};

/** Generate a code for `kind` using the owner's configuration (legacy when unset). */
export const generateCode = (cfg: CodesConfig | null | undefined, kind: CodeKind, ctx: CodeContext = {}): string => {
  const t = resolveTemplate(cfg, kind);
  if (!t) return legacyCode(kind);
  const out = renderTemplate(t, ctx, cfg!.scopes);
  return out || legacyCode(kind);
};

/**
 * A monotonic clock for bulk generation: each call returns a millisecond value
 * strictly greater than the previous one so timestamp-based codes stay unique
 * even when hundreds of rows are generated inside one millisecond.
 */
export const monotonicClock = () => {
  let last = 0;
  return () => {
    const now = Date.now();
    last = now > last ? now : last + 1;
    return last;
  };
};

// ---------- descriptions & previews (editor) ----------
const SAMPLE_SCOPES: ScopeAbbreviations = {
  churches: { sample: 'STM' }, services: { sample: 'SS' }, classes: { sample: 'C1' },
};
const SAMPLE_CTX: CodeContext = { churchId: 'sample', serviceId: 'sample', classId: 'sample', now: 1702655732293 };

/** Deterministic preview (fixed moment + sample abbreviations) for the editor. */
export const previewTemplate = (t: CodeTemplate, opts?: { scopes?: ScopeAbbreviations; ctx?: CodeContext }): string => {
  const scopes = opts?.scopes ?? SAMPLE_SCOPES;
  const ctx = { ...SAMPLE_CTX, ...(opts?.ctx ?? {}) };
  const segs = t.parts.map((p) => {
    if (p.type === 'random') {
      // stable-looking sample instead of noise
      const alphabet = CHARSETS[p.charset] ?? ALNUM;
      let s = '';
      for (let i = 0; i < p.length; i++) s += alphabet[(i * 7 + 3) % alphabet.length];
      return s;
    }
    return renderPart(p, ctx, scopes);
  }).filter((s) => s.length > 0);
  return applyCase(segs.join(t.separator), t.case);
};

export const partLabel = (p: CodePart): string => {
  switch (p.type) {
    case 'text': return p.value ? `«${p.value}»` : 'نص';
    case 'timestamp': return 'الوقت';
    case 'date': return `التاريخ ${p.format}`;
    case 'random': return `عشوائي ×${p.length}`;
    case 'church': return 'الكنيسة';
    case 'service': return 'الخدمة';
    case 'class': return 'الفصل';
  }
};

export const describeTemplate = (t: CodeTemplate): string =>
  t.parts.length === 0 ? 'قالب فارغ' : t.parts.map(partLabel).join(t.separator ? ` ${t.separator} ` : ' + ');

export const MODE_LABELS: Record<GeneratorMode, string> = {
  default: 'النظام الافتراضي',
  custom: 'تصميم خاص',
  legacy: 'الطريقة الأصلية',
};

/** does the template use any scope part (→ the editor nudges the owner to fill abbreviations) */
export const usesScopes = (t: CodeTemplate): boolean => t.parts.some(isScopePart);

// ---------- normalize (never trust stored JSON) ----------
const DATE_FORMATS: DateFormat[] = ['YYYYMMDD', 'YYMMDD', 'DDMMYYYY', 'DDMMYY', 'YYYYMM', 'YYMM', 'YYYY', 'YY'];
const CHARSET_KEYS: RandomCharset[] = ['alnum', 'digits', 'letters', 'hex'];
const CASES: CodeCase[] = ['none', 'upper', 'lower'];
const MODES: GeneratorMode[] = ['default', 'custom', 'legacy'];

const isObj = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);

const normalizePart = (raw: unknown): CodePart | null => {
  if (!isObj(raw)) return null;
  switch (raw.type) {
    case 'text': {
      const value = sanitizeSegment(typeof raw.value === 'string' ? raw.value : '', MAX_TEXT_LENGTH);
      return value ? { type: 'text', value } : null;
    }
    case 'timestamp': return { type: 'timestamp' };
    case 'date': {
      const f = raw.format as DateFormat;
      return { type: 'date', format: DATE_FORMATS.includes(f) ? f : 'YYYYMMDD' };
    }
    case 'random': {
      const n = Number(raw.length);
      const length = Number.isFinite(n) ? Math.min(MAX_RANDOM, Math.max(MIN_RANDOM, Math.round(n))) : 6;
      const c = raw.charset as RandomCharset;
      return { type: 'random', length, charset: CHARSET_KEYS.includes(c) ? c : 'alnum' };
    }
    case 'church': case 'service': case 'class':
      return { type: raw.type, fallback: sanitizeSegment(typeof raw.fallback === 'string' ? raw.fallback : '', MAX_ABBREVIATION_LENGTH) };
    default: return null;
  }
};

export const normalizeTemplate = (raw: unknown): CodeTemplate => {
  if (!isObj(raw)) return { parts: [], separator: '-', case: 'none' };
  const parts = (Array.isArray(raw.parts) ? raw.parts : [])
    .map(normalizePart)
    .filter((p): p is CodePart => !!p)
    .slice(0, MAX_PARTS);
  const separator = typeof raw.separator === 'string' ? sanitizeSegment(raw.separator, MAX_SEPARATOR_LENGTH) : '-';
  const c = raw.case as CodeCase;
  return { parts, separator, case: CASES.includes(c) ? c : 'none' };
};

const normalizeAbbrMap = (raw: unknown): Record<string, string> => {
  const out: Record<string, string> = {};
  if (!isObj(raw)) return out;
  for (const [k, v] of Object.entries(raw)) {
    if (typeof v !== 'string') continue;
    const s = sanitizeSegment(v.trim(), MAX_ABBREVIATION_LENGTH);
    if (s) out[k] = s;
  }
  return out;
};

export const normalizeCodes = (raw: unknown): CodesConfig => {
  if (!isObj(raw)) return DEFAULT_CODES;
  const def = normalizeTemplate(raw.default);
  const gensRaw = isObj(raw.generators) ? raw.generators : {};
  const generators = {} as Record<CodeKind, GeneratorConfig>;
  for (const kind of CODE_KINDS) {
    const g = gensRaw[kind];
    if (!isObj(g)) { generators[kind] = { mode: 'legacy' }; continue; }
    const mode = MODES.includes(g.mode as GeneratorMode) ? (g.mode as GeneratorMode) : 'legacy';
    const cfg: GeneratorConfig = { mode };
    if (g.template !== undefined) cfg.template = normalizeTemplate(g.template);
    generators[kind] = cfg;
  }
  const sc = isObj(raw.scopes) ? raw.scopes : {};
  return {
    version: 1,
    default: def.parts.length > 0 ? def : DEFAULT_TEMPLATE,
    generators,
    scopes: {
      churches: normalizeAbbrMap(sc.churches),
      services: normalizeAbbrMap(sc.services),
      classes: normalizeAbbrMap(sc.classes),
    },
  };
};

/** true when at least one generator does NOT use the legacy built-in generator */
export const codesActive = (cfg: CodesConfig): boolean =>
  CODE_KINDS.some((k) => cfg.generators[k]?.mode !== 'legacy');

/** short human summary for the hub */
export const summarizeCodes = (cfg: CodesConfig, customized: boolean): string => {
  if (!customized || !codesActive(cfg)) return 'الطريقة الأصلية لكل الأكواد (P-XXXXXXXX …)';
  const def = previewTemplate(cfg.default);
  const custom = CODE_KINDS.filter((k) => cfg.generators[k]?.mode === 'custom').length;
  const legacy = CODE_KINDS.filter((k) => cfg.generators[k]?.mode === 'legacy').length;
  const extras = [
    custom ? `${custom} تصميم خاص` : '',
    legacy ? `${legacy} بالطريقة الأصلية` : '',
  ].filter(Boolean).join(' · ');
  return `الافتراضي: ${def}${extras ? ` — ${extras}` : ''}`;
};
