#!/bin/bash
# =====================================================================
# Build ONE combined SQL file from every migration in supabase/migrations/
# so a brand-new database can be created in a single run.
#
#   supabase/build_full_schema.sh            -> writes supabase/full_schema.sql
#   supabase/build_full_schema.sh out.sql    -> custom output path
#
# What it does:
#   * concatenates every <version>_<name>.sql in version order (the same
#     order the Supabase CLI uses: legacy 0001 -> 0051, then the
#     timestamped YYYYMMDDHHMMSS_* files that follow)
#   * includes 0002_bootstrap_owner.sql → a fresh install gets the default
#     owner (code 000000 / password 000000 — change it after first login)
#   * keeps `alter type ... add value` (0005) in place — nothing in the
#     migrations references the new value afterwards, so it is safe both in
#     autocommit mode and in a single transaction (the enum is created by
#     0001 inside the same run)
#   * strips per-file `begin;` / `commit;` so the whole file can be run as
#     one statement batch (Supabase SQL editor / psql -1)
# =====================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${1:-supabase/full_schema.sql}"
MIG_DIR="supabase/migrations"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

files=()
for f in "$MIG_DIR"/*.sql; do
  b=$(basename "$f")
  # same filter as the Supabase CLI: <digits>_<name>.sql
  [[ "$b" =~ ^[0-9]+_.*\.sql$ ]] || { echo "skip (not a migration name): $b" >&2; continue; }
  files+=("$f")
done
last=$(basename "${files[-1]}"); last=${last%%_*}

{
  cat <<HDR
-- =====================================================================
-- FULL SCHEMA — all migrations combined (0001 → ${last})
-- Generated by supabase/build_full_schema.sh on $(date -u +%Y-%m-%d)
-- Source: ${#files[@]} files in ${MIG_DIR}/
--
-- HOW TO USE (new Supabase project):
--   1. SQL Editor → paste / run this whole file once.
--   2. Authentication → Providers → Email → disable "Confirm email".
--   3. Log in with code 000000 / password 000000 (created by 0002) and
--      change both in الإعدادات → تعديل بياناتي.
--   (Preferred for new projects: 'supabase link' + 'supabase db push'
--    applies supabase/migrations/ and records them in the history table.)
--
-- HOW TO USE (local Postgres / CI):
--   psql -d app -f supabase/tests/local_shim.sql
--   psql -d app -v ON_ERROR_STOP=1 -f supabase/full_schema.sql
--
-- NOTES:
--   * Every per-file begin;/commit; has been removed so the file is one
--     batch. Run it with autocommit (SQL editor default) or psql -1.
--   * 0005 adds the enum value 'suspended'. No later statement in this
--     file references it, so it needs no separate step.
-- =====================================================================
HDR

  for f in "${files[@]}"; do
    b=$(basename "$f")
    printf '\n\n-- #####################################################################\n'
    printf -- '-- ##  %s\n' "$b"
    printf -- '-- #####################################################################\n\n'
    # strip bare begin;/commit; lines
    sed -E \
      -e '/^\s*(begin|commit)\s*;\s*(--.*)?$/Id' \
      "$f"
  done
} > "$TMP"

mv "$TMP" "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines, ${#files[@]} migrations, last = $last)"
