// Custom Cloudflare Worker entry (wrangler.jsonc → "main").
//
// @opennextjs/cloudflare generates `.open-next/worker.js`, which only exports
// a `fetch` handler. We wrap it to add a `scheduled` handler so the two daily
// jobs that Vercel runs through vercel.json crons also run on Cloudflare:
//
//   30 2 * * *  → GET /api/backup/cron            (scheduled backups)
//    0 3 * * *  → GET /api/notifications/dispatch  (push notifications)
//
// The cron simply performs an internal HTTP request against the same Worker
// (the route handlers already implement the logic and the CRON_SECRET check),
// so the behaviour is identical on both platforms. When CRON_SECRET is set as
// a Worker secret it is sent as `Authorization: Bearer <secret>` — exactly
// what Vercel Cron does.
//
// See https://opennext.js.org/cloudflare/howtos/custom-worker

// @ts-ignore — `.open-next/worker.js` is generated by `npm run cf:build`
import openNextHandler from '../.open-next/worker.js';

interface Env {
  ASSETS: { fetch: typeof fetch };
  CRON_SECRET?: string;
  /** Public origin used for cron self-requests (defaults to the Worker's own URL). */
  CRON_ORIGIN?: string;
  [key: string]: unknown;
}

interface ScheduledEvent {
  cron: string;
  scheduledTime: number;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

/** cron expression (as written in wrangler.jsonc "triggers.crons") → route */
const CRON_ROUTES: Record<string, string> = {
  '30 2 * * *': '/api/backup/cron',
  '0 3 * * *': '/api/notifications/dispatch',
};

async function runCron(path: string, env: Env, ctx: ExecutionContext): Promise<void> {
  // Any https origin works: the OpenNext fetch handler routes on the path and
  // the origin resolver only needs a well-formed URL.
  const origin = env.CRON_ORIGIN || 'https://cron.internal';
  const headers = new Headers({ 'user-agent': 'cloudflare-cron' });
  if (env.CRON_SECRET) headers.set('authorization', `Bearer ${env.CRON_SECRET}`);
  const request = new Request(new URL(path, origin), { method: 'GET', headers });
  const res: Response = await openNextHandler.fetch(request, env, ctx);
  const text = await res.text().catch(() => '');
  console.log(`[cron] GET ${path} → ${res.status} ${text.slice(0, 500)}`);
}

export default {
  fetch: openNextHandler.fetch,

  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    const path = CRON_ROUTES[event.cron];
    if (!path) {
      console.warn(`[cron] no route registered for "${event.cron}"`);
      return;
    }
    ctx.waitUntil(runCron(path, env, ctx));
  },
};

// Required only when the DO queue / DO tag cache are enabled in
// open-next.config.ts — harmless otherwise, keeps the export surface identical
// to the generated worker.
// @ts-ignore — generated at build time
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../.open-next/worker.js';
