-- =====================================================================
-- 0040: CODE SYSTEM (تخصيص التطبيق → نظام الأكواد)
--
-- The OWNER designs how the codes generated by the app look. A code is a
-- TEMPLATE = ordered PARTS joined by a SEPARATOR, e.g.
--
--     [text "P"] - [timestamp]                        →  P-1702655732293
--     [church] - [class] - [date YYMMDD] - [random 4] →  STM-C1-231215-4F7K
--
-- Stored in `app_settings` (0035 — owner-write / all-read / realtime):
--
--   key = 'codes' → {
--     version: 1,
--     default:    { parts: [...], separator: '-', case: 'none'|'upper'|'lower' },
--     generators: {                       -- one entry per generator in the app
--       person:     { mode: 'default'|'custom'|'legacy', template? },
--       servant:    { ... },
--       store_item: { ... },
--       ticket:     { ... }               -- rendered HERE (render_code) by the trigger
--     },
--     scopes: {                           -- abbreviations used by church/service/class parts
--       churches: { "<uuid>": "STM" }, services: { ... }, classes: { ... }
--     }
--   }
--
--   parts[].type ∈ text {value} · timestamp · date {format} · random {length, charset}
--                  · church | service | class {fallback}
--
-- The app renders codes in `src/lib/code-templates.ts` (`renderTemplate`);
-- `public.render_code()` below is its SQL mirror so DATABASE-generated codes
-- (occasion tickets) follow the same design. `public.code_settings()` lets the
-- anonymous SIGNUP page read the configuration (the servant code is generated
-- before the account exists). Idempotent — safe to re-run.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Validation — the owner can never save a malformed code system
-- ---------------------------------------------------------------------
create or replace function public.validate_code_template(t jsonb, label text)
returns void language plpgsql immutable as $$
declare p jsonb; n int;
begin
  if jsonb_typeof(t) <> 'object' then
    raise exception 'app_settings.codes: % must be an object', label;
  end if;
  if jsonb_typeof(t -> 'parts') <> 'array' or jsonb_array_length(t -> 'parts') > 8 then
    raise exception 'app_settings.codes: %.parts must be an array (max 8)', label;
  end if;
  if t ? 'separator' and (jsonb_typeof(t -> 'separator') <> 'string'
      or length(t ->> 'separator') > 3 or (t ->> 'separator') !~ '^[A-Za-z0-9._-]*$') then
    raise exception 'app_settings.codes: %.separator must be ≤ 3 safe characters', label;
  end if;
  if t ? 'case' and (t ->> 'case') not in ('none', 'upper', 'lower') then
    raise exception 'app_settings.codes: %.case invalid', label;
  end if;
  for p in select * from jsonb_array_elements(t -> 'parts') loop
    if jsonb_typeof(p) <> 'object' then raise exception 'app_settings.codes: %.parts[] must be objects', label; end if;
    case p ->> 'type'
      when 'text' then
        if coalesce(p ->> 'value', '') !~ '^[A-Za-z0-9._-]{1,12}$' then
          raise exception 'app_settings.codes: %: text part must be 1–12 safe characters', label;
        end if;
      when 'timestamp' then null;
      when 'date' then
        if coalesce(p ->> 'format', '') not in ('YYYYMMDD','YYMMDD','DDMMYYYY','DDMMYY','YYYYMM','YYMM','YYYY','YY') then
          raise exception 'app_settings.codes: %: invalid date format', label;
        end if;
      when 'random' then
        n := (p ->> 'length')::int;
        if n is null or n < 1 or n > 16 then raise exception 'app_settings.codes: %: random length must be 1–16', label; end if;
        if coalesce(p ->> 'charset', 'alnum') not in ('alnum', 'digits', 'letters', 'hex') then
          raise exception 'app_settings.codes: %: invalid random charset', label;
        end if;
      when 'church', 'service', 'class' then
        if coalesce(p ->> 'fallback', '') !~ '^[A-Za-z0-9._-]{0,8}$' then
          raise exception 'app_settings.codes: %: scope fallback must be ≤ 8 safe characters', label;
        end if;
      else
        raise exception 'app_settings.codes: %: unknown part type %', label, p ->> 'type';
    end case;
  end loop;
end $$;

create or replace function public.validate_app_settings()
returns trigger language plpgsql as $$
declare g text; gen jsonb; kv record;
begin
  if jsonb_typeof(new.value) <> 'object' then
    raise exception 'app_settings.value must be a JSON object (key %)', new.key;
  end if;
  if new.key = 'names' then
    if exists (
      select 1 from jsonb_each(new.value) kv
       where jsonb_typeof(kv.value) <> 'string'
          or length(kv.value #>> '{}') = 0
          or length(kv.value #>> '{}') > 30
    ) then
      raise exception 'app_settings.names: every label must be a 1–30 character string';
    end if;
  end if;
  if new.key = 'widgets' then
    if jsonb_typeof(new.value -> 'items') <> 'array'
       or jsonb_array_length(new.value -> 'items') > 40 then
      raise exception 'app_settings.widgets: items must be an array (max 40)';
    end if;
  end if;
  if new.key = 'codes' then
    perform public.validate_code_template(new.value -> 'default', 'default');
    if jsonb_array_length(new.value -> 'default' -> 'parts') = 0 then
      raise exception 'app_settings.codes: default template needs at least one part';
    end if;
    if new.value ? 'generators' then
      if jsonb_typeof(new.value -> 'generators') <> 'object' then
        raise exception 'app_settings.codes: generators must be an object';
      end if;
      for g, gen in select * from jsonb_each(new.value -> 'generators') loop
        if g not in ('person', 'servant', 'store_item', 'ticket') then
          raise exception 'app_settings.codes: unknown generator %', g;
        end if;
        if coalesce(gen ->> 'mode', 'legacy') not in ('default', 'custom', 'legacy') then
          raise exception 'app_settings.codes: generator % has an invalid mode', g;
        end if;
        if gen ? 'template' then perform public.validate_code_template(gen -> 'template', g); end if;
        if gen ->> 'mode' = 'custom' and jsonb_array_length(coalesce(gen -> 'template' -> 'parts', '[]'::jsonb)) = 0 then
          raise exception 'app_settings.codes: generator % is custom but has no parts', g;
        end if;
      end loop;
    end if;
    if new.value ? 'scopes' then
      for kv in
        select m.key as grp, e.key as id, e.value as abbr
          from jsonb_each(new.value -> 'scopes') m
          cross join lateral jsonb_each(m.value) e
      loop
        if kv.grp not in ('churches', 'services', 'classes') then
          raise exception 'app_settings.codes: unknown scope group %', kv.grp;
        end if;
        if jsonb_typeof(kv.abbr) <> 'string' or (kv.abbr #>> '{}') !~ '^[A-Za-z0-9._-]{1,8}$' then
          raise exception 'app_settings.codes: abbreviation for % must be 1–8 safe characters', kv.id;
        end if;
      end loop;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_validate_app_settings on public.app_settings;
create trigger trg_validate_app_settings before insert or update on public.app_settings
for each row execute function public.validate_app_settings();

-- ---------------------------------------------------------------------
-- 2. render_code — SQL mirror of renderTemplate() (src/lib/code-templates.ts)
-- ---------------------------------------------------------------------
create or replace function public.random_code_chars(n int, charset text)
returns text language plpgsql volatile as $$
declare
  alphabet text := case charset
    when 'digits'  then '0123456789'
    when 'letters' then 'ABCDEFGHJKLMNPQRSTUVWXYZ'
    when 'hex'     then '0123456789ABCDEF'
    else 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789' end;
  out text := '';
  i int;
begin
  for i in 1..greatest(1, least(16, coalesce(n, 6))) loop
    out := out || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return out;
end $$;

create or replace function public.format_code_date(d timestamptz, fmt text)
returns text language sql immutable as $$
  select to_char(d at time zone 'Africa/Cairo', case fmt
    when 'YYYYMMDD' then 'YYYYMMDD'
    when 'YYMMDD'   then 'YYMMDD'
    when 'DDMMYYYY' then 'DDMMYYYY'
    when 'DDMMYY'   then 'DDMMYY'
    when 'YYYYMM'   then 'YYYYMM'
    when 'YYMM'     then 'YYMM'
    when 'YYYY'     then 'YYYY'
    when 'YY'       then 'YY'
    else 'YYYYMMDD' end)
$$;

-- t = template object · scopes = codes.scopes · the three ids = generation context
create or replace function public.render_code(
  t jsonb, scopes jsonb, p_church uuid, p_service uuid, p_class uuid, p_now timestamptz default clock_timestamp())
returns text language plpgsql volatile as $$
declare
  p jsonb; seg text; segs text[] := '{}'; sep text; kase text; res text; sid text;
begin
  if t is null or jsonb_typeof(t -> 'parts') <> 'array' then return null; end if;
  sep  := coalesce(t ->> 'separator', '-');
  kase := coalesce(t ->> 'case', 'none');
  for p in select * from jsonb_array_elements(t -> 'parts') loop
    case p ->> 'type'
      when 'text'      then seg := p ->> 'value';
      when 'timestamp' then seg := (floor(extract(epoch from p_now) * 1000))::bigint::text;
      when 'date'      then seg := public.format_code_date(p_now, p ->> 'format');
      when 'random'    then seg := public.random_code_chars((p ->> 'length')::int, p ->> 'charset');
      when 'church'    then
        sid := p_church::text;
        seg := coalesce(nullif(scopes -> 'churches' ->> sid, ''), p ->> 'fallback', '');
      when 'service'   then
        sid := p_service::text;
        seg := coalesce(nullif(scopes -> 'services' ->> sid, ''), p ->> 'fallback', '');
      when 'class'     then
        sid := p_class::text;
        seg := coalesce(nullif(scopes -> 'classes' ->> sid, ''), p ->> 'fallback', '');
      else seg := '';
    end case;
    if coalesce(seg, '') <> '' then segs := segs || seg; end if;
  end loop;
  res := array_to_string(segs, sep);
  if kase = 'upper' then res := upper(res); elsif kase = 'lower' then res := lower(res); end if;
  return nullif(res, '');
end $$;

-- the template a generator actually uses — null = legacy built-in
create or replace function public.code_template_for(p_kind text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare cfg jsonb; gen jsonb; mode text;
begin
  select value into cfg from public.app_settings where key = 'codes';
  if cfg is null then return null; end if;
  gen  := cfg -> 'generators' -> p_kind;
  mode := coalesce(gen ->> 'mode', 'legacy');
  if mode = 'legacy' then return null; end if;
  if mode = 'custom' and jsonb_array_length(coalesce(gen -> 'template' -> 'parts', '[]'::jsonb)) > 0 then
    return gen -> 'template';
  end if;
  if jsonb_array_length(coalesce(cfg -> 'default' -> 'parts', '[]'::jsonb)) > 0 then
    return cfg -> 'default';
  end if;
  return null;
end $$;
revoke all on function public.code_template_for(text) from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- 3. Occasion ticket code → follows the owner's design (legacy when unset)
-- ---------------------------------------------------------------------
create or replace function public.occasion_new_ticket_code(p_church uuid default null, p_service uuid default null, p_class uuid default null)
returns text language plpgsql volatile security definer set search_path = public as $$
declare v text; i integer := 0; t jsonb; scopes jsonb;
begin
  t := public.code_template_for('ticket');
  select value -> 'scopes' into scopes from public.app_settings where key = 'codes';
  loop
    if t is not null then
      v := public.render_code(t, coalesce(scopes, '{}'::jsonb), p_church, p_service, p_class);
      -- a template without any random / timestamp part could repeat → add a tiny suffix on retry
      if i > 0 then v := v || '-' || public.random_code_chars(2, 'alnum'); end if;
    end if;
    if v is null then
      v := 'T-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
    end if;
    exit when not exists (select 1 from public.occasion_registrations r where r.ticket_code = v);
    i := i + 1;
    if i > 20 then raise exception 'ticket_code_collision'; end if;
    perform pg_sleep(0.001);   -- lets a timestamp-based template move forward
  end loop;
  return v;
end $$;
revoke all on function public.occasion_new_ticket_code(uuid, uuid, uuid) from public, anon, authenticated;
-- drop the old zero-arg overload (0032/0033) so the trigger resolves unambiguously
drop function if exists public.occasion_new_ticket_code();

create or replace function public.occasion_registration_fill()
returns trigger language plpgsql security definer set search_path = public as $$
declare e public.enrollments; o public.occasions;
begin
  select * into e from public.enrollments where id = new.enrollment_id;
  if not found then raise exception 'enrollment_not_found' using errcode = 'P0002'; end if;
  select * into o from public.occasions where id = new.occasion_id;
  if not found then raise exception 'occasion_not_found' using errcode = 'P0002'; end if;
  if not (o.church_id = e.church_id
          and (o.service_id is null or o.service_id = e.service_id)
          and (o.class_id   is null or o.class_id   = e.class_id)) then
    raise exception 'out_of_scope' using errcode = 'P0001';
  end if;
  new.person_id  := e.person_id;
  new.church_id  := e.church_id;
  new.service_id := e.service_id;
  new.class_id   := e.class_id;
  if new.ticket_code is null or length(trim(new.ticket_code)) = 0 then
    new.ticket_code := public.occasion_new_ticket_code(e.church_id, e.service_id, e.class_id);
  end if;
  return new;
end $$;

drop trigger if exists trg_occ_reg_fill on public.occasion_registrations;
create trigger trg_occ_reg_fill before insert on public.occasion_registrations
for each row execute function public.occasion_registration_fill();

-- ---------------------------------------------------------------------
-- 4. Fallback person code inside add_person_and_enroll (no code given)
--    follows the 'person' generator instead of 24 hex chars.
-- ---------------------------------------------------------------------
create or replace function public.new_person_code(p_church uuid, p_service uuid, p_class uuid)
returns text language plpgsql volatile security definer set search_path = public as $$
declare v text; i int := 0; t jsonb; scopes jsonb;
begin
  t := public.code_template_for('person');
  select value -> 'scopes' into scopes from public.app_settings where key = 'codes';
  loop
    if t is not null then
      v := public.render_code(t, coalesce(scopes, '{}'::jsonb), p_church, p_service, p_class);
      if i > 0 then v := v || '-' || public.random_code_chars(2, 'alnum'); end if;
    end if;
    if v is null then v := 'P-' || public.random_code_chars(8, 'alnum'); end if;
    exit when not exists (select 1 from public.persons p where p.national_id = v);
    i := i + 1;
    if i > 20 then raise exception 'person_code_collision'; end if;
    perform pg_sleep(0.001);
  end loop;
  return v;
end $$;
revoke all on function public.new_person_code(uuid, uuid, uuid) from public, anon, authenticated;

-- same body as 0011, only the fallback code changed (hex → new_person_code)
create or replace function public.add_person_and_enroll(
  p_church uuid,
  p_service uuid,
  p_class uuid,
  p_name text,
  p_national_id text default null,
  p_gender text default null,
  p_birthdate date default null,
  p_phone text default null,
  p_address text default null,
  p_notes text default null,
  p_image_url text default null,
  p_points integer default 0
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_nid text;
  v_person public.persons%rowtype;
  v_person_created boolean := false;
  v_enrollment_id uuid;
  v_already boolean := false;
begin
  if public.my_role() is null then
    raise exception 'not_approved' using errcode = '42501';
  end if;
  if not public.can_access(p_church, p_service, p_class) then
    raise exception 'no_access' using errcode = '42501';
  end if;
  if coalesce(trim(p_name), '') = '' then
    raise exception 'name_required';
  end if;
  if p_gender is not null and p_gender not in ('male', 'female') then
    raise exception 'invalid_gender';
  end if;

  v_nid := nullif(trim(p_national_id), '');
  if v_nid is null then
    v_nid := public.new_person_code(p_church, p_service, p_class);
  end if;

  select * into v_person from public.persons where national_id = v_nid;

  if not found then
    insert into public.persons (
      national_id, name, gender, birthdate, phone, address, notes,
      image_url, created_by, edited_by
    ) values (
      v_nid, trim(p_name), p_gender, p_birthdate,
      nullif(trim(coalesce(p_phone, '')), ''),
      nullif(trim(coalesce(p_address, '')), ''),
      nullif(trim(coalesce(p_notes, '')), ''),
      p_image_url, auth.uid(), auth.uid()
    ) returning * into v_person;
    v_person_created := true;
  else
    -- Person exists: fill in the blanks only (never overwrite existing data)
    update public.persons set
      gender    = coalesce(gender, p_gender),
      birthdate = coalesce(birthdate, p_birthdate),
      phone     = coalesce(phone, nullif(trim(coalesce(p_phone, '')), '')),
      address   = coalesce(address, nullif(trim(coalesce(p_address, '')), '')),
      notes     = coalesce(notes, nullif(trim(coalesce(p_notes, '')), '')),
      image_url = coalesce(image_url, p_image_url),
      edited_by = auth.uid(),
      edited_at = now()
    where id = v_person.id;
  end if;

  -- Register the enrollment (person may already be in this class)
  insert into public.enrollments (person_id, church_id, service_id, class_id, points, created_by, edited_by)
  values (v_person.id, p_church, p_service, p_class, greatest(coalesce(p_points, 0), 0), auth.uid(), auth.uid())
  on conflict (person_id, class_id) do nothing
  returning id into v_enrollment_id;

  if v_enrollment_id is null then
    v_already := true;
    select id into v_enrollment_id from public.enrollments
     where person_id = v_person.id and class_id = p_class;
  end if;

  return jsonb_build_object(
    'person_id', v_person.id,
    'enrollment_id', v_enrollment_id,
    'national_id', v_nid,
    'person_created', v_person_created,
    'already_enrolled', v_already
  );
end $$;

-- ---------------------------------------------------------------------
-- 5. code_settings — read-only access for the anonymous SIGNUP page
--    (the servant generates his code before he has an account)
-- ---------------------------------------------------------------------
create or replace function public.code_settings()
returns jsonb language sql stable security definer set search_path = public as $$
  select value from public.app_settings where key = 'codes'
$$;
grant execute on function public.code_settings() to anon, authenticated;

notify pgrst, 'reload schema';

commit;
