-- =====================================================================
-- FAMILY MODULE — v2: user-set family code · search persons · new member
--
--   * The family CODE is chosen by the servant when creating the family
--     (typed · scanned · generated by نظام الأكواد — new generator `family`).
--     The DB still fills one when none is sent. A family code may never be
--     a PERSON code (the scanner must tell them apart) → trigger check.
--   * `family_code_lookup(code)`   — live check while typing
--   * `family_search_persons(q)`   — name / phone / code search over the
--                                    persons the caller may see, with each
--                                    person's current family + places
--   * `family_add_member(family, person_id, relation, move)` — add an
--     EXISTING person picked from the search (by-code RPC now delegates)
--   * `family_add_new_member(...)` — create the person (+ optional
--     enrollment in church → service → class) AND add him to the family
--     in ONE transaction
--   * app_settings.codes validator accepts the `family` generator
-- Idempotent. Run after 20260924120000_families.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Code system — accept generator `family`
-- ---------------------------------------------------------------------
create or replace function public.validate_app_settings()
returns trigger language plpgsql as $$
declare g text; gen jsonb; sc record;
begin
  if jsonb_typeof(new.value) <> 'object' then
    raise exception 'app_settings.value must be a JSON object (key %)', new.key;
  end if;
  if new.key = 'names' then
    if exists (
      select 1 from jsonb_each(new.value) kv
       where jsonb_typeof(kv.value) <> 'string'
          or length(kv.value #>> '{}') = 0
          or length(kv.value #>> '{}') > 30
    ) then
      raise exception 'app_settings.names: every label must be a 1–30 character string';
    end if;
  end if;
  if new.key = 'widgets' then
    if jsonb_typeof(new.value -> 'items') <> 'array'
       or jsonb_array_length(new.value -> 'items') > 40 then
      raise exception 'app_settings.widgets: items must be an array (max 40)';
    end if;
  end if;
  if new.key = 'codes' then
    perform public.validate_code_template(new.value -> 'default', 'default');
    if jsonb_array_length(new.value -> 'default' -> 'parts') = 0 then
      raise exception 'app_settings.codes: default template needs at least one part';
    end if;
    if new.value ? 'generators' then
      if jsonb_typeof(new.value -> 'generators') <> 'object' then
        raise exception 'app_settings.codes: generators must be an object';
      end if;
      for g, gen in select * from jsonb_each(new.value -> 'generators') loop
        if g not in ('person', 'servant', 'store_item', 'ticket', 'family') then
          raise exception 'app_settings.codes: unknown generator %', g;
        end if;
        if coalesce(gen ->> 'mode', 'legacy') not in ('default', 'custom', 'legacy') then
          raise exception 'app_settings.codes: generator % has an invalid mode', g;
        end if;
        if gen ? 'template' then perform public.validate_code_template(gen -> 'template', g); end if;
        if gen ->> 'mode' = 'custom' and jsonb_array_length(coalesce(gen -> 'template' -> 'parts', '[]'::jsonb)) = 0 then
          raise exception 'app_settings.codes: generator % is custom but has no parts', g;
        end if;
      end loop;
    end if;
    if new.value ? 'scopes' then
      for sc in
        select m.key as grp, e.key as id, e.value as abbr
          from jsonb_each(new.value -> 'scopes') m
          cross join lateral jsonb_each(m.value) e
      loop
        if sc.grp not in ('churches', 'services', 'classes') then
          raise exception 'app_settings.codes: unknown scope group %', sc.grp;
        end if;
        if jsonb_typeof(sc.abbr) <> 'string' or length(sc.abbr #>> '{}') > 12 then
          raise exception 'app_settings.codes: abbreviation of % must be a string of at most 12 characters', sc.id;
        end if;
      end loop;
    end if;
  end if;
  return new;
end $$;

-- ---------------------------------------------------------------------
-- 2. Family code trigger — normalise + refuse a PERSON code
-- ---------------------------------------------------------------------
create or replace function public.families_fill_code()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.code is null or length(trim(new.code)) = 0 then
    new.code := public.family_new_code();
  else
    new.code := trim(new.code);
    if length(new.code) > 60 then
      raise exception 'code_too_long' using errcode = '22023';
    end if;
    if exists (select 1 from public.persons p where p.national_id = new.code) then
      raise exception 'code_is_person' using errcode = '23505',
        detail = 'A family code cannot equal the code of a person';
    end if;
  end if;
  new.name := trim(new.name);
  if tg_op = 'INSERT' and new.created_by is null then
    new.created_by := auth.uid();
  end if;
  if tg_op = 'INSERT' and new.edited_by is null then
    new.edited_by := auth.uid();
  end if;
  return new;
end $$;

-- ---------------------------------------------------------------------
-- 3. family_code_lookup(code) — live check while typing / after a scan
--    { code, free, family: {id, name} | null, person: {id, name} | null }
-- ---------------------------------------------------------------------
create or replace function public.family_code_lookup(p_code text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_code text := trim(coalesce(p_code, ''));
  v_fam  record;
  v_per  record;
begin
  if not public.family_can('family.view') then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if v_code = '' then
    return jsonb_build_object('code', '', 'free', false, 'family', null, 'person', null);
  end if;
  select id, name into v_fam from public.families where code = v_code;
  select id, name into v_per from public.persons where national_id = v_code;
  return jsonb_build_object(
    'code', v_code,
    'free', (v_fam.id is null and v_per.id is null),
    'family', case when v_fam.id is null then null else jsonb_build_object('id', v_fam.id, 'name', v_fam.name) end,
    'person', case when v_per.id is null then null else jsonb_build_object('id', v_per.id, 'name', v_per.name) end
  );
end $$;
revoke all on function public.family_code_lookup(text) from public, anon;
grant execute on function public.family_code_lookup(text) to authenticated;

-- ---------------------------------------------------------------------
-- 4. family_search_persons(q, limit) — persons the caller may see
--    (owner: everyone; others: ≥ 1 enrollment in a scope he can access,
--    or a person he created). Each row: person · family {id,name} | null
--    · places [{church_id, service_id, class_id}] (scoped).
-- ---------------------------------------------------------------------
create or replace function public.family_search_persons(p_query text, p_limit integer default 30)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_q     text := nullif(trim(coalesce(p_query, '')), '');
  v_limit integer := least(greatest(coalesce(p_limit, 30), 1), 100);
  v_out   jsonb;
begin
  if not public.family_can('family.view') then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if v_q is null or length(v_q) < 2 then
    return '[]'::jsonb;
  end if;

  with hits as (
    select p.*
      from public.persons p
     where (p.name ilike '%' || v_q || '%'
            or p.phone ilike '%' || v_q || '%'
            or p.national_id ilike '%' || v_q || '%')
       and (
         public.is_owner()
         or p.created_by = auth.uid()
         or exists (select 1 from public.enrollments e
                     where e.person_id = p.id
                       and public.can_access(e.church_id, e.service_id, e.class_id))
       )
     order by (p.national_id = v_q) desc, p.name collate "C"
     limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'person', to_jsonb(h),
           'family', (select jsonb_build_object('id', f.id, 'name', f.name)
                        from public.family_members m join public.families f on f.id = m.family_id
                       where m.person_id = h.id),
           'places', coalesce((
             select jsonb_agg(jsonb_build_object('church_id', e.church_id, 'service_id', e.service_id, 'class_id', e.class_id, 'kind', e.kind) order by e.created_at)
               from public.enrollments e
              where e.person_id = h.id
                and public.can_access(e.church_id, e.service_id, e.class_id)), '[]'::jsonb)
         ) order by (h.national_id = v_q) desc, h.name collate "C"), '[]'::jsonb)
    into v_out
    from hits h;
  return v_out;
end $$;
revoke all on function public.family_search_persons(text, integer) from public, anon;
grant execute on function public.family_search_persons(text, integer) to authenticated;
comment on function public.family_search_persons(text, integer) is
  'بحث عن أشخاص (اسم · هاتف · كود) في نطاق المستخدم لإضافتهم إلى عائلة — مع عائلتهم الحالية وأماكنهم';

-- ---------------------------------------------------------------------
-- 5. family_add_member(family, person_id, relation, move) — the core
--    add; the by-code RPC delegates to it.
-- ---------------------------------------------------------------------
create or replace function public.family_add_member(
  p_family   uuid,
  p_person   uuid,
  p_relation text default null,
  p_move     boolean default false
) returns jsonb
language plpgsql volatile security definer set search_path = public as $$
declare
  v_person  public.persons%rowtype;
  v_other   public.families%rowtype;
  v_member  public.family_members%rowtype;
  v_moved   jsonb := null;
begin
  if not public.family_can('family.manage') then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if not exists (select 1 from public.families f where f.id = p_family) then
    raise exception 'family_not_found' using errcode = 'P0001';
  end if;
  if not public.family_visible(p_family) then
    raise exception 'no_access' using errcode = '42501';
  end if;
  if p_relation is not null and p_relation not in (
    'father', 'mother', 'son', 'daughter', 'brother', 'sister',
    'grandfather', 'grandmother', 'husband', 'wife', 'other') then
    raise exception 'invalid_relation' using errcode = '22023';
  end if;

  select * into v_person from public.persons p where p.id = p_person;
  if not found then
    raise exception 'person_not_found' using errcode = 'P0002';
  end if;

  select * into v_member from public.family_members m where m.person_id = v_person.id;
  if found then
    if v_member.family_id = p_family then
      raise exception 'already_member' using errcode = 'P0001';
    end if;
    select * into v_other from public.families f where f.id = v_member.family_id;
    if not p_move then
      raise exception 'in_other_family' using errcode = 'P0001',
        detail = coalesce(v_other.name, ''), hint = v_member.family_id::text;
    end if;
    delete from public.family_members where id = v_member.id;
    v_moved := jsonb_build_object('id', v_other.id, 'name', v_other.name);
  end if;

  insert into public.family_members (family_id, person_id, relation, created_by)
  values (p_family, v_person.id, p_relation, auth.uid())
  returning * into v_member;

  update public.families set edited_at = now(), edited_by = auth.uid() where id = p_family;

  return jsonb_build_object(
    'member_id', v_member.id,
    'relation',  v_member.relation,
    'person',    to_jsonb(v_person),
    'moved_from', v_moved
  );
end $$;
revoke all on function public.family_add_member(uuid, uuid, text, boolean) from public, anon;
grant execute on function public.family_add_member(uuid, uuid, text, boolean) to authenticated;

create or replace function public.family_add_member_by_code(
  p_family   uuid,
  p_code     text,
  p_relation text default null,
  p_move     boolean default false
) returns jsonb
language plpgsql volatile security definer set search_path = public as $$
declare v_person uuid;
begin
  if not public.family_can('family.manage') then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  select id into v_person from public.persons p where p.national_id = trim(coalesce(p_code, ''));
  if v_person is null then
    raise exception 'person_not_found' using errcode = 'P0002';
  end if;
  return public.family_add_member(p_family, v_person, p_relation, p_move);
end $$;

-- ---------------------------------------------------------------------
-- 6. family_add_new_member — create the person (+ optional enrollment)
--    and add him to the family in one transaction.
--    With p_class → add_person_and_enroll (same rules as إضافة مخدوم:
--    upsert by code, enrollment in church → service → class).
--    Without a class → a bare person row (parents who are in no service);
--    the code is required then (a bare person has no other identity).
--    Errors: forbidden · family_not_found · no_access · name_required ·
--            code_required · code_taken (code belongs to a FAMILY) ·
--            already_member · in_other_family (DETAIL = name)
-- ---------------------------------------------------------------------
create or replace function public.family_add_new_member(
  p_family      uuid,
  p_name        text,
  p_national_id text default null,
  p_gender      text default null,
  p_birthdate   date default null,
  p_phone       text default null,
  p_address     text default null,
  p_notes       text default null,
  p_image_url   text default null,
  p_church      uuid default null,
  p_service     uuid default null,
  p_class       uuid default null,
  p_relation    text default null,
  p_move        boolean default false
) returns jsonb
language plpgsql volatile security definer set search_path = public, extensions as $$
declare
  v_code   text := nullif(trim(coalesce(p_national_id, '')), '');
  v_name   text := nullif(trim(coalesce(p_name, '')), '');
  v_person uuid;
  v_res    jsonb;
  v_add    jsonb;
  v_created boolean := false;
begin
  if not public.family_can('family.manage') then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if not exists (select 1 from public.families f where f.id = p_family) then
    raise exception 'family_not_found' using errcode = 'P0001';
  end if;
  if not public.family_visible(p_family) then
    raise exception 'no_access' using errcode = '42501';
  end if;
  if v_name is null then
    raise exception 'name_required' using errcode = '22023';
  end if;
  if v_code is not null and exists (select 1 from public.families f where f.code = v_code) then
    raise exception 'code_taken' using errcode = '23505';
  end if;
  if p_gender is not null and p_gender not in ('male', 'female') then
    raise exception 'invalid_gender' using errcode = '22023';
  end if;

  if p_class is not null then
    if p_church is null or p_service is null then
      raise exception 'invalid_scope' using errcode = '22023';
    end if;
    -- same path as إضافة مخدوم (validates scope + access, upserts by code)
    v_res := public.add_person_and_enroll(
      p_church, p_service, p_class, v_name, v_code, p_gender, p_birthdate,
      p_phone, p_address, p_notes, p_image_url, 0, null);
    v_person  := (v_res ->> 'person_id')::uuid;
    v_created := coalesce((v_res ->> 'person_created')::boolean, false);
  else
    if v_code is null then
      raise exception 'code_required' using errcode = '22023';
    end if;
    select id into v_person from public.persons where national_id = v_code;
    if v_person is null then
      insert into public.persons (national_id, name, gender, birthdate, phone, address, notes, image_url, created_by, edited_by)
      values (v_code, v_name, p_gender, p_birthdate, p_phone, p_address, p_notes, p_image_url, auth.uid(), auth.uid())
      returning id into v_person;
      v_created := true;
    else
      -- existing person: fill the blanks only (typed data never overwrites)
      update public.persons set
        gender    = coalesce(gender, p_gender),
        birthdate = coalesce(birthdate, p_birthdate),
        phone     = coalesce(phone, p_phone),
        address   = coalesce(address, p_address),
        notes     = coalesce(notes, p_notes),
        image_url = coalesce(image_url, p_image_url),
        edited_at = now(), edited_by = auth.uid()
      where id = v_person;
    end if;
  end if;

  v_add := public.family_add_member(p_family, v_person, p_relation, p_move);
  return v_add || jsonb_build_object(
    'person_created', v_created,
    'enrollment_id', v_res ->> 'enrollment_id',
    'already_enrolled', coalesce((v_res ->> 'already_enrolled')::boolean, false)
  );
end $$;
revoke all on function public.family_add_new_member(uuid, text, text, text, date, text, text, text, text, uuid, uuid, uuid, text, boolean) from public, anon;
grant execute on function public.family_add_new_member(uuid, text, text, text, date, text, text, text, text, uuid, uuid, uuid, text, boolean) to authenticated;
comment on function public.family_add_new_member(uuid, text, text, text, date, text, text, text, text, uuid, uuid, uuid, text, boolean) is
  'إنشاء شخص جديد (مع تسجيله في فصل اختيارياً) وإضافته إلى العائلة في عملية واحدة';

commit;
